### PR TITLE
Update Nx to v17

### PR DESCRIPTION
**Pull request by rathpc**
This updates Nx to `v17.1.2` with all migrations ran.

Various other dependencies were updated to also support Nx v17:
- `@jscutlery/semver` updated to `^4.0.0`
- `@swc/core` updated to `^1.3.85`
- `ngx-deploy-npm` updated to `^7.1.0`
- `nx-remotecache-custom` updated to `^17.0.0`

**BREAKING CHANGE**: requires Nx `>=17.0.0`

### CODE REVIEW

**Comment by rathpc** [comment]
@robinpellegrims I recently got nx-remotecache-custom updated to support nx v17 so I wanted to get this repo updated to use that new version and support v17 as well. Please take a look and let me know if you need me to change anything. Thanks!

**Comment by robinpellegrims** [comment]
looks like we're running into ci issues again due to @e-square/nx-affected-matrix not being compatible with recent versions of nx..

**Comment by rathpc** [comment]
> looks like we're running into ci issues again due to @e-square/nx-affected-matrix not being compatible with recent versions of nx..

Yea I noticed that too. Looks like either we have to update that action or the workflow here to not use the action anymore. Up to you...

**Comment by rathpc** [comment]
I spent a few minutes trying to estimate a LOE for updating that action. It would be a pretty involved refactor because most of the logic is before the major changes happened in 16.9.0 and a lot would need to change. Not as simple as a migrate unfortunately

**Comment by rathpc** [comment]
@robinpellegrims I've almost got everything sorted out, just a few more tweaks and I think we should be good. I will let you know when it is all set to review again.

**Comment by rathpc** [comment]
@robinpellegrims ok, it is finally ready. I had to tweak a few more things and remove the aws updates because for some reason jest.mocked was not handling the S3 client the same way and that felt out of scope for the purpose of this PR anyway.

Additionally, the deploy jobs are failing because forks likely don't have access to your secrets if I remember from last time.

**Comment by robinpellegrims** [comment]
> @robinpellegrims ok, it is finally ready. I had to tweak a few more things and remove the aws updates because for some reason jest.mocked was not handling the S3 client the same way and that felt out of scope for the purpose of this PR anyway.
> 
> Additionally, the deploy jobs are failing because forks likely don't have access to your secrets if I remember from last time.

That's really awesome @rathpc, thanks a lot! Also I like the clean & separate commits! :-)

Regarding the deploy jobs, don't worry about them indeed. Initially I placed those apps in this repository since I anticipated limited interest in the published packages. However, as interest has grown, I plan to migrate these jobs elsewhere as they're more obstructive than beneficial. Additionally, it makes more sense to separate CI and CD anyway.

I'll try to review and merge before tomorrow night (probably won't have much time before).

Thanks again!

**Review by robinpellegrims — APPROVED** [review]

**Pull request merged**
