### PR TITLE
feat: update package to force version bump

### PR DESCRIPTION
**Pull request by rathpc**
BREAKING CHANGE: Minimum Nx version is now >=16.0.0

### CODE REVIEW

**Comment by robinpellegrims** [comment]
Thanks!
I wonder if I should unpublish 2.1.3.. Is the change not backwards compatible with repositories using nx 15?

**Comment by rathpc** [comment]
And I will have to do the same I did here for the other packages because the latest commits there have the same issue, they should be a breaking change but weren't. Opening another PR shortly but you can unpublish the latest release and delete tags for the others as well

**Comment by rathpc** [comment]
Actually, I just realized those probably don't matter as much as they are still pre v1. Let me know if you want those fixed though

**Comment by robinpellegrims** [comment]
Ok, I unpublished @pellegrims/nx-remotecache-s3@2.1.3 and @pellegrims/eslint-config-angular@0.0.9 and removed the github releases and tags so it should be ok now.

**Comment by robinpellegrims** [comment]
> Actually, I just realized those probably don't matter as much as they are still pre v1. Let me know if you want those fixed though

Indeed, i'm probably the only one using that eslint config package so don't worry about those :-)

Again, thanks a lot for pushing everything forward!

**Pull request merged**
